[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["verix*"]

[project]
name = "verix"
version = "0.0.2"
description = "A framework for complex SV benchmarking and harmonization"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "networkx",
    "numpy",
    "pandas",
    "plotnine",
    "pysam",
    "tqdm",
]

[project.scripts]
verix = "verix.main:main"